### ISSUE TITLE
Config files inheritance

### ISSUE THREAD

**Issue by Lysoun** [4sh/datamaintain#152]
Config files can inherit other config files and override their properties. To declare a parent file in a child file, a property is set with the relative or absolute path of the parent file. 
Datamaintain does multiple executions with the different files declared.

+ add name (optional) to config

**Comment by driccio** [comment]
Hi,

To manage relative path, we need to define some rules :
- With embedded usage : the path will be relative to the 'user.dir'.
- With cli usage : the path will be the current path (equivalent of pwd). 

But knowing default behaviour can be annoying,  @nroulon and me suggest to add a configuration 'working.directory.path' (and it's equivalent with cli command) that allows to define the working directory. This path will be absolute.

So now we have a working directory, if the scan Path is relative, then it will be relative to this working directory. This can impact existing projects. Be careful.

Then, in order to help user of datamaintain we will had a cli command that allow to get the effective configuration used (i.e. the merged configuration, with absolute and normalized paths).

As we can name the config, we also will log when a file config is loaded by printing it's name (if there is one) and it's path.

**Comment by driccio** [comment]
if a config file is given to cli without working directory, then the working directory will be the directory containing the config file

**Comment by driccio** [comment]
Remaining work : 
- Update documentation
