### ISSUE TITLE
"Cannot run program mongo : Argument list too long" when use --mongo-save-output with large output

### ISSUE THREAD

**Issue by mrenou4sh** [4sh/datamaintain#90]
We use directly command mongo to store executed-script, but if the output is too large, we explode the buffer of the command line.

Moreover, a mongo document max size  is 16 Mb, may be we should store output in grid fs ?

**Comment by Lysoun** [comment]
This bug was discussed today with the team and will be tackled in the next release. For now, to ensure Datamaintain does not crash when it happens, an output max size is going to be added. Do you have an example that could be used to test that size? @mrenou4sh 

I am creating an issue about the logs that will be resolved.

**Comment by mrenou4sh** [comment]
I have some script in my projects but it's hard to reproduce with them. The simpler way to reprodure is to write a script which prints lot of text. 

Moreover, the saved content should be stored into gridfs to avoid the 16 mo limit.
